// // ============================================================
// ADAM DNA Deployment Specification
// Platform: Azure Local (On-Premises Failover)
// Company: NetStreamX
// Generated: 2026-03-29
// ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
// ============================================================
// This file was auto-generated by the ADAM DNA Deployment Tool
// from a completed ADAM DNA Questionnaire.
//
// ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
// GPU Agents: 42
// ============================================================
// Azure Local Deployment - On-Premises Failover for ADAM
// ACTIVATION: Only when both Azure and AWS are simultaneously unavailable,
// or for data residency isolation requirements.

targetScope = 'resourceGroup'

@description('Azure Local cluster name')
param clusterName string = 'adam-local-netstreamx'

@description('Location')
param location string = resourceGroup().location

@description('Environment')
param environment string = 'production'

// AKS-HCI for critical-path agents only
module aksHci 'modules/aks-hci.bicep' = {
  name: 'adam-aks-hci'
  params: {
    clusterName: clusterName
    location: location
    environment: environment
  }
}

// Azure Arc for unified management
module arcServices 'modules/arc-services.bicep' = {
  name: 'adam-arc-services'
  params: {
    clusterName: clusterName
    location: location
  }
}
