# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM AI Services - Azure OpenAI for agent reasoning

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "tags" { type = map(string) }

resource "azurerm_cognitive_account" "adam_openai" {
  name                = "oai-adam-${var.company_slug}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  kind                = "OpenAI"
  sku_name            = "S0"

  custom_subdomain_name = "adam-${var.company_slug}-${var.environment}"

  network_acls {
    default_action = "Deny"
  }

  tags = var.tags
}

# Primary reasoning model (Governor Agents, Domain Governors)
resource "azurerm_cognitive_deployment" "reasoning" {
  name                 = "adam-reasoning-primary"
  cognitive_account_id = azurerm_cognitive_account.adam_openai.id

  model {
    format  = "OpenAI"
    name    = "gpt-4o"
    version = "2024-11-20"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 450  # 450K TPM
  }
}

# Fast execution model (Work Group agents, routine operations)
resource "azurerm_cognitive_deployment" "execution" {
  name                 = "adam-execution-fast"
  cognitive_account_id = azurerm_cognitive_account.adam_openai.id

  model {
    format  = "OpenAI"
    name    = "gpt-4o-mini"
    version = "2024-07-18"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 1000  # 1M TPM
  }
}

# Deep reasoning model (Digital Twins, Risk analysis)
resource "azurerm_cognitive_deployment" "deep_reasoning" {
  name                 = "adam-deep-reasoning"
  cognitive_account_id = azurerm_cognitive_account.adam_openai.id

  model {
    format  = "OpenAI"
    name    = "o1"
    version = "2024-12-17"
  }

  sku {
    name     = "GlobalStandard"
    capacity = 100
  }
}
