# ============================================================
# ADAM DNA Deployment Specification
# Platform: ADAM Configuration Bundle (Platform-Agnostic)
# Company: NetStreamX
# Generated: 2026-04-26
# ADAM Version: 1.7 | DNA Questionnaire Version: 1.1 | BOSS Formulas: v3.3
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool v1.2
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 81+ (reference) | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM BOSS Scoring - OPA/Rego Policy (BOSS Formulas v3.3)
# 7 canonical dimensions; Priority Tier weights sum to 24.0
# Company: NetStreamX
# ============================================================
#
# ──────────────────────────────────────────────────────────────────────────────
# REGO AUTHORING DISCIPLINE — REQUIRED READING BEFORE EDITING THIS FILE
# ──────────────────────────────────────────────────────────────────────────────
# This module REQUIRES OPA Rego v1 grammar. The bundle MUST be loaded by an
# OPA process invoked with the `--v1-compatible` flag (see
# `iac/compose/docker-compose.yml` and `iac/k3d/opa-deployment.yaml`).
#
# This is the authoritative remediation path for the seven OPA 0.64.x v0
# grammar booby-traps surfaced during the NetStreamX initial deployment
# (audit log Section 0210 → 0210.G, 2026-04-23 → 2026-04-24). The original
# v1.1 BOSS rego shipped with `import future.keywords.in` and inline `if`/
# `else` operators, both of which are silently misinterpreted under OPA v0
# default mode. v1 mode resolves all seven failure classes:
#
#   1. Brace-bodied conditional bindings nested in another rule body
#   2. Top-level `name := value` with non-literal value (function call, infix)
#   3. `import future.keywords.in` does NOT enable `some x in y` iteration
#   4. Even `import future.keywords` is not honoured by 0.64.1 in v0 mode
#   5. `not x[_]` (negation of iteration variable) — unsafe-var error
#   6. Bare-reference comprehension body — type-checker reads `|` as set-union
#   7. `:=` and `=` inside comprehension body are both rejected by v0 parser
#
# In v1 mode (`import rego.v1`), every construct in this file is grammatically
# valid AND type-safe. Do NOT remove `import rego.v1`. Do NOT downgrade the
# OPA invocation to drop `--v1-compatible`.
#
# Cross-reference: ADAM Book v1.7 Appendix L "OPA Rego Authoring Standards"
# Cross-reference: ADAM - Support Documents/ADAM - OPA Rego Authoring
#                  Standards v1.0.docx
# ──────────────────────────────────────────────────────────────────────────────

package adam.boss

import rego.v1

# Canonical BOSS v3.3 Priority Tier weights (denominator Σ = 24.0)
# Top=5.0 (Security only), Very High=4.0, High=3.0, Medium=2.0
weights := {
	"security_impact": 5.0,
	"sovereignty_action": 4.0,
	"financial_exposure": 4.0,
	"regulatory_impact": 3.0,
	"reputational_risk": 3.0,
	"rights_certainty": 3.0,
	"doctrinal_alignment": 2.0,
}

# Canonical weight total (5+4+4+3+3+3+2 = 24.0). Held as a literal constant
# rather than `sum(...)` so the doctrine value is explicit at the policy
# level and the type-inference surface is reduced. If `weights` is ever
# modified, this constant MUST be updated in lockstep — `boss/boss_score.py`
# carries the parity test that will fail if drift is introduced.
weight_total := 24.0

# Weighted sum over 7 dimensions. Unrolled to an explicit per-dimension
# expression — no comprehension. This is bulletproof against the bare-
# reference / `|`-as-set-union ambiguity discovered in audit log 0210.E,
# AND bulletproof against the comprehension-body assignment-operator
# rejections discovered in 0210.F. Algebraic equivalence to the
# comprehension form is preserved exactly.
weighted_sum := s if {
	s := (input.dimensions.security_impact * 5.0) +
		(input.dimensions.sovereignty_action * 4.0) +
		(input.dimensions.financial_exposure * 4.0) +
		(input.dimensions.regulatory_impact * 3.0) +
		(input.dimensions.reputational_risk * 3.0) +
		(input.dimensions.rights_certainty * 3.0) +
		(input.dimensions.doctrinal_alignment * 2.0)
}

raw_score := r if {
	r := weighted_sum / weight_total
}

# Maximum dimension across all 7 — explicit list literal to `max()`,
# again no comprehension.
max_dim := m if {
	m := max([
		input.dimensions.security_impact,
		input.dimensions.sovereignty_action,
		input.dimensions.financial_exposure,
		input.dimensions.regulatory_impact,
		input.dimensions.reputational_risk,
		input.dimensions.rights_certainty,
		input.dimensions.doctrinal_alignment,
	])
}

# Critical-Dimension Override: if any dim > 75 AND (max_dim − 10) > raw_score,
# the composite is floored at (max_dim − 10). This prevents a single severe
# dimension from being averaged-away into a low composite.
critical_override if {
	max_dim > 75
	(max_dim - 10) > raw_score
}

base_score := raw_score if not critical_override

base_score := s if {
	critical_override
	s := max_dim - 10
}

# Non-Idempotent Penalty: +15 flat additive (NOT a multiplier).
default penalty := 0
penalty := 15 if input.is_non_idempotent

# Composite score with hard ceiling at 100.
composite_score := s if {
	s := min([base_score + penalty, 100])
}

# ──────────────────────────────────────────────────────────────────────────────
# Routing tier (SOAP / MODERATE / ELEVATED / HIGH / OHSHAT per ADAM book v1.7)
# ──────────────────────────────────────────────────────────────────────────────
# Sacred-boundary engagement always forces OHSHAT regardless of composite —
# implemented as a guarded rule with explicit precedence. Each composite-band
# rule includes `not sacred_boundary_engaged` and the negation of every
# higher-priority composite guard, so no two rules can ever fire simultaneously.
# Eliminates any risk of `eval_conflict_error` at request time. (Audit log
# Section 0210 / B1.b.)
default routing_tier := "soap"

routing_tier := "ohshat" if sacred_boundary_engaged

routing_tier := "ohshat" if {
	not sacred_boundary_engaged
	composite_score > 75
}

routing_tier := "high" if {
	not sacred_boundary_engaged
	composite_score > 50
	composite_score <= 75
}

routing_tier := "elevated" if {
	not sacred_boundary_engaged
	composite_score > 30
	composite_score <= 50
}

routing_tier := "moderate" if {
	not sacred_boundary_engaged
	composite_score > 10
	composite_score <= 30
}

# Sacred-boundary detection — engaged if the constraint string appears anywhere
# in the intent's constraint array. Uses v1 `some x in collection` iteration.
sacred_boundary_engaged if {
	some c in input.intent.constraints
	c == "sacred_boundary_engaged"
}

# Escalation targets per tier (canonical ADAM routing).
escalation_targets["ohshat"] := ["CEO", "All Directors", "Automatic Safe-Mode"]

escalation_targets["high"] := ["Relevant Domain Director", "4-Hour Max Response"]

escalation_targets["elevated"] := ["Domain Governor Agent", "Structured Exception Packet"]

escalation_targets["moderate"] := ["Autonomous Execution", "Enhanced Logging", "Post-Hoc Review"]

escalation_targets["soap"] := ["Autonomous Execution", "Minimal Logging"]

# Intent validation — required fields populated.
intent_valid if {
	input.intent.intent_id != ""
	input.intent.source.role != ""
	count(input.intent.desired_outcomes) > 0
}

# Director authorisation check (5-Director Constitution + CPO/CTO if seated).
valid_director_ids := ["ceo", "cfo", "legal_director", "market_director", "ciso", "cpo", "cto"]

director_authorized if {
	input.intent.source.role == "director"
	some d in valid_director_ids
	d == input.intent.source.director_id
}

director_authorized if {
	count(input.intent.source.delegation_chain) > 0
}
