# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.47"
    }
  }
  backend "azurerm" {
    resource_group_name  = "adam-tfstate-rg"
    storage_account_name = "adamtfstate${var.environment}"
    container_name       = "tfstate"
    key                  = "adam-netstreamx.tfstate"
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = false
    }
  }
  subscription_id = var.subscription_id
}

# ============================================================
# Resource Group - ADAM Governance Plane
# ============================================================
resource "azurerm_resource_group" "adam_governance" {
  name     = "rg-adam-governance-${var.environment}"
  location = var.primary_region
  tags     = local.common_tags
}

# ============================================================
# Resource Group - ADAM Agent Mesh (Execution Plane)
# ============================================================
resource "azurerm_resource_group" "adam_agents" {
  name     = "rg-adam-agents-${var.environment}"
  location = var.primary_region
  tags     = local.common_tags
}

# ============================================================
# Resource Group - ADAM Data Plane
# ============================================================
resource "azurerm_resource_group" "adam_data" {
  name     = "rg-adam-data-${var.environment}"
  location = var.primary_region
  tags     = local.common_tags
}

locals {
  common_tags = {
    "adam-company"     = "NetStreamX"
    "adam-version"     = "0.4"
    "adam-platform"    = "azure-primary"
    "managed-by"       = "adam-dna-deployment-tool"
    "environment"      = var.environment
    "cost-center"      = "adam-governance"
    "data-classification" = "confidential"
  }
}

# ============================================================
# Module: Networking (Hub-Spoke with sovereignty boundaries)
# ============================================================
module "networking" {
  source              = "./modules/networking"
  resource_group_name = azurerm_resource_group.adam_governance.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  address_space       = var.vnet_address_space
  tags                = local.common_tags
}

# ============================================================
# Module: Identity (Entra ID managed identities, zero-trust)
# ============================================================
module "identity" {
  source              = "./modules/identity"
  resource_group_name = azurerm_resource_group.adam_governance.name
  location            = var.primary_region
  environment         = var.environment
  agent_count         = 82
  tags                = local.common_tags
}

# ============================================================
# Module: AKS (Agent Mesh container orchestration)
# ============================================================
module "aks" {
  source              = "./modules/aks"
  resource_group_name = azurerm_resource_group.adam_agents.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  vnet_subnet_id      = module.networking.aks_subnet_id
  identity_id         = module.identity.aks_identity_id
  total_vcpus         = 3180
  total_ram_gb        = 12720
  gpu_agent_count     = 42
  tags                = local.common_tags
}

# ============================================================
# Module: Cosmos DB (CORE Graph - Gremlin API)
# ============================================================
module "cosmosdb" {
  source              = "./modules/cosmosdb"
  resource_group_name = azurerm_resource_group.adam_data.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  multi_region_writes = true
  secondary_regions   = var.secondary_regions
  tags                = local.common_tags
}

# ============================================================
# Module: Evidence Store (Flight Recorder - immutable)
# ============================================================
module "evidence_store" {
  source              = "./modules/evidence-store"
  resource_group_name = azurerm_resource_group.adam_data.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  retention_days      = 2555  # 7 years
  tags                = local.common_tags
}

# ============================================================
# Module: Key Vault (Cryptographic Authorization Vault)
# ============================================================
module "keyvault" {
  source              = "./modules/keyvault"
  resource_group_name = azurerm_resource_group.adam_governance.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  hsm_enabled         = true
  tags                = local.common_tags
}

# ============================================================
# Module: Service Bus (Agent Orchestration Messaging)
# ============================================================
module "servicebus" {
  source              = "./modules/servicebus"
  resource_group_name = azurerm_resource_group.adam_governance.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  tags                = local.common_tags
}

# ============================================================
# Module: Monitoring (OpenTelemetry + Grafana)
# ============================================================
module "monitoring" {
  source              = "./modules/monitoring"
  resource_group_name = azurerm_resource_group.adam_governance.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  tags                = local.common_tags
}

# ============================================================
# Module: Azure OpenAI & AI Services
# ============================================================
module "ai_services" {
  source              = "./modules/ai-services"
  resource_group_name = azurerm_resource_group.adam_agents.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  tags                = local.common_tags
}

# ============================================================
# Module: Azure Data Explorer (BOSS Score History)
# ============================================================
module "data_explorer" {
  source              = "./modules/data-explorer"
  resource_group_name = azurerm_resource_group.adam_data.name
  location            = var.primary_region
  environment         = var.environment
  company_slug        = "netstreamx"
  tags                = local.common_tags
}

# ============================================================
# Outputs
# ============================================================
output "adam_governance_rg" {
  value = azurerm_resource_group.adam_governance.name
}

output "aks_cluster_name" {
  value = module.aks.cluster_name
}

output "cosmosdb_endpoint" {
  value     = module.cosmosdb.endpoint
  sensitive = true
}

output "evidence_store_endpoint" {
  value     = module.evidence_store.endpoint
  sensitive = true
}

output "keyvault_uri" {
  value     = module.keyvault.vault_uri
  sensitive = true
}
