# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================

variable "subscription_id" {
  description = "Azure subscription ID for ADAM deployment"
  type        = string
}

variable "environment" {
  description = "Deployment environment (dev, staging, production)"
  type        = string
  default     = "production"
}

variable "primary_region" {
  description = "Primary Azure region for ADAM governance plane"
  type        = string
  default     = "westeurope"
}

variable "secondary_regions" {
  description = "Secondary Azure regions for multi-region deployment"
  type        = list(string)
  default     = ["eastus", "southeastasia"]
}

variable "vnet_address_space" {
  description = "VNET address space for ADAM networking"
  type        = list(string)
  default     = ["10.0.0.0/8"]
}

variable "aks_vm_size_system" {
  description = "VM size for AKS system node pool"
  type        = string
  default     = "Standard_D8s_v5"
}

variable "aks_vm_size_gpu" {
  description = "VM size for AKS GPU node pool (Digital Twins, ML agents)"
  type        = string
  default     = "Standard_NC24ads_A100_v4"
}

variable "adam_company_name" {
  description = "Company name from DNA Questionnaire"
  type        = string
  default     = "NetStreamX"
}
