// // ============================================================
// ADAM DNA Deployment Specification
// Platform: Microsoft Azure (Primary)
// Company: NetStreamX
// Generated: 2026-03-29
// ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
// ============================================================
// This file was auto-generated by the ADAM DNA Deployment Tool
// from a completed ADAM DNA Questionnaire.
//
// ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
// GPU Agents: 42
// ============================================================
// ADAM CORE Engine Bicep Module

param location string
param environment string
param companySlug string

// Cosmos DB for CORE Graph
resource cosmosAccount 'Microsoft.DocumentDB/databaseAccounts@2023-11-15' = {
  name: 'cosmos-adam-core-${companySlug}-${environment}'
  location: location
  kind: 'GlobalDocumentDB'
  properties: {
    databaseAccountOfferType: 'Standard'
    enableAutomaticFailover: true
    enableMultipleWriteLocations: true
    capabilities: [
      { name: 'EnableGremlin' }
    ]
    consistencyPolicy: {
      defaultConsistencyLevel: 'BoundedStaleness'
      maxIntervalInSeconds: 300
      maxStalenessPrefix: 100000
    }
    locations: [
      { locationName: location, failoverPriority: 0 }
    ]
  }
}

// Key Vault for Cryptographic Authorization Vault
resource keyVault 'Microsoft.KeyVault/vaults@2023-07-01' = {
  name: 'kv-adam-${companySlug}-${environment}'
  location: location
  properties: {
    sku: { family: 'A', name: 'premium' }
    tenantId: subscription().tenantId
    enableRbacAuthorization: true
    enablePurgeProtection: true
    softDeleteRetentionInDays: 90
    networkAcls: {
      defaultAction: 'Deny'
      bypass: 'AzureServices'
    }
  }
}
