# ============================================================
# ADAM DNA Deployment Specification
# Platform: Google Cloud Platform
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Vertex AI - Agent reasoning services

variable "project_id" { type = string }
variable "region" { type = string }
variable "company_slug" { type = string }

resource "google_vertex_ai_endpoint" "adam_reasoning" {
  name         = "adam-reasoning-${var.company_slug}"
  display_name = "ADAM Reasoning Endpoint"
  location     = var.region
  project      = var.project_id
}
