# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Evidence Store - Flight Recorder (immutable, append-only)

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "retention_days" { type = number }
variable "tags" { type = map(string) }

# Immutable Blob Storage for Flight Recorder
resource "azurerm_storage_account" "flight_recorder" {
  name                     = "stadamfr${var.company_slug}${var.environment}"
  resource_group_name      = var.resource_group_name
  location                 = var.location
  account_tier             = "Standard"
  account_replication_type = "GZRS"  # Geo-zone-redundant
  min_tls_version          = "TLS1_2"
  allow_nested_items_to_be_public = false

  blob_properties {
    versioning_enabled = true
    delete_retention_policy {
      days = var.retention_days
    }
    container_delete_retention_policy {
      days = var.retention_days
    }
  }

  immutability_policy {
    state                         = "Unlocked"
    period_since_creation_in_days = var.retention_days
    allow_protected_append_writes = true  # Append-only
  }

  tags = var.tags
}

# Azure Confidential Ledger for cryptographic evidence chains
resource "azurerm_confidential_ledger" "adam_ledger" {
  name                = "cl-adam-${var.company_slug}-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  ledger_type         = "Private"

  azuread_based_service_principal {
    principal_id = "" # Set via identity module
    ledger_role_name = "Administrator"
    tenant_id    = ""
  }

  tags = var.tags
}

output "endpoint" {
  value = azurerm_storage_account.flight_recorder.primary_blob_endpoint
}
