# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM EKS Module - Container orchestration for agent mesh

variable "environment" { type = string }
variable "company_slug" { type = string }
variable "vpc_id" { type = string }
variable "private_subnets" { type = list(string) }
variable "total_vcpus" { type = number }
variable "gpu_agent_count" { type = number }

resource "aws_eks_cluster" "adam" {
  name     = "eks-adam-${var.company_slug}-${var.environment}"
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "1.29"

  vpc_config {
    subnet_ids              = var.private_subnets
    endpoint_private_access = true
    endpoint_public_access  = false
  }

  encryption_config {
    provider { key_arn = aws_kms_key.eks.arn }
    resources = ["secrets"]
  }
}

resource "aws_kms_key" "eks" {
  description = "ADAM EKS secrets encryption"
}

resource "aws_iam_role" "eks_cluster" {
  name = "adam-eks-cluster-role-${var.environment}"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow",
      Principal = { Service = "eks.amazonaws.com" } }]
  })
}

# Governance Node Group
resource "aws_eks_node_group" "governance" {
  cluster_name    = aws_eks_cluster.adam.name
  node_group_name = "adam-governance"
  node_role_arn   = aws_iam_role.eks_node.arn
  subnet_ids      = var.private_subnets
  instance_types  = ["m6i.4xlarge"]

  scaling_config {
    desired_size = 3
    min_size     = 3
    max_size     = 10
  }

  labels = { "adam/plane" = "governance", "adam/tier" = "sovereign" }
}

# Agent Mesh Node Group
resource "aws_eks_node_group" "agent_mesh" {
  cluster_name    = aws_eks_cluster.adam.name
  node_group_name = "adam-agents"
  node_role_arn   = aws_iam_role.eks_node.arn
  subnet_ids      = var.private_subnets
  instance_types  = ["m6i.8xlarge"]

  scaling_config {
    desired_size = 5
    min_size     = 3
    max_size     = 50
  }

  labels = { "adam/plane" = "execution", "adam/agent-type" = "cpu" }
}

# GPU Node Group
resource "aws_eks_node_group" "gpu" {
  cluster_name    = aws_eks_cluster.adam.name
  node_group_name = "adam-gpu"
  node_role_arn   = aws_iam_role.eks_node.arn
  subnet_ids      = var.private_subnets
  instance_types  = ["p4d.24xlarge"]
  ami_type        = "AL2_x86_64_GPU"

  scaling_config {
    desired_size = 2
    min_size     = 1
    max_size     = 20
  }

  labels = { "adam/plane" = "execution", "adam/agent-type" = "gpu" }
}

resource "aws_iam_role" "eks_node" {
  name = "adam-eks-node-role-${var.environment}"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{ Action = "sts:AssumeRole", Effect = "Allow",
      Principal = { Service = "ec2.amazonaws.com" } }]
  })
}
