// // ============================================================
// ADAM DNA Deployment Specification
// Platform: Microsoft Azure (Primary)
// Company: NetStreamX
// Generated: 2026-03-29
// ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
// ============================================================
// This file was auto-generated by the ADAM DNA Deployment Tool
// from a completed ADAM DNA Questionnaire.
//
// ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
// GPU Agents: 42
// ============================================================

targetScope = 'subscription'

@description('Primary Azure region')
param primaryRegion string = 'westeurope'

@description('Environment name')
param environment string = 'production'

@description('Company name from DNA Questionnaire')
param companyName string = 'NetStreamX'

var companySlug = toLower(replace(replace(companyName, ' ', '-'), ',', ''))

// Resource Groups
resource rgGovernance 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: 'rg-adam-governance-${environment}'
  location: primaryRegion
  tags: {
    'adam-company': companyName
    'adam-version': '0.4'
    'adam-platform': 'azure-primary'
  }
}

resource rgAgents 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: 'rg-adam-agents-${environment}'
  location: primaryRegion
  tags: {
    'adam-company': companyName
    'adam-version': '0.4'
  }
}

resource rgData 'Microsoft.Resources/resourceGroups@2023-07-01' = {
  name: 'rg-adam-data-${environment}'
  location: primaryRegion
  tags: {
    'adam-company': companyName
    'adam-version': '0.4'
  }
}

// ADAM CORE Engine Module
module adamCore 'modules/adam-core.bicep' = {
  name: 'adam-core-deployment'
  scope: rgGovernance
  params: {
    location: primaryRegion
    environment: environment
    companySlug: companySlug
  }
}

output governanceResourceGroup string = rgGovernance.name
output agentsResourceGroup string = rgAgents.name
output dataResourceGroup string = rgData.name
