# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Networking Module - Hub-Spoke with sovereignty boundaries
# Governance components use private endpoints only

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "address_space" { type = list(string) }
variable "tags" { type = map(string) }

resource "azurerm_virtual_network" "adam_hub" {
  name                = "vnet-adam-hub-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  address_space       = var.address_space
  tags                = var.tags
}

# Governance Subnet (CORE Engine, Policy Enforcement, BOSS, Flight Recorder)
resource "azurerm_subnet" "governance" {
  name                 = "snet-adam-governance"
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.adam_hub.name
  address_prefixes     = ["10.1.0.0/16"]
  private_endpoint_network_policies_enabled = true
}

# Agent Mesh Subnet (AKS cluster for 81 agents)
resource "azurerm_subnet" "aks" {
  name                 = "snet-adam-aks"
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.adam_hub.name
  address_prefixes     = ["10.2.0.0/16"]
}

# Data Plane Subnet (Cosmos DB, Storage, Data Explorer)
resource "azurerm_subnet" "data" {
  name                 = "snet-adam-data"
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.adam_hub.name
  address_prefixes     = ["10.3.0.0/16"]
  private_endpoint_network_policies_enabled = true
}

# Human Interface Subnet (Director Portal, Explain-Back)
resource "azurerm_subnet" "human_interface" {
  name                 = "snet-adam-human-interface"
  resource_group_name  = var.resource_group_name
  virtual_network_name = azurerm_virtual_network.adam_hub.name
  address_prefixes     = ["10.4.0.0/16"]
}

# NSG: Governance - no public internet exposure
resource "azurerm_network_security_group" "governance" {
  name                = "nsg-adam-governance-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags

  security_rule {
    name                       = "DenyInternetInbound"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "Internet"
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "AllowVnetInbound"
    priority                   = 200
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "VirtualNetwork"
    destination_address_prefix = "VirtualNetwork"
  }
}

output "aks_subnet_id" {
  value = azurerm_subnet.aks.id
}

output "governance_subnet_id" {
  value = azurerm_subnet.governance.id
}

output "data_subnet_id" {
  value = azurerm_subnet.data.id
}
