# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Service Bus - Agent orchestration messaging

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "tags" { type = map(string) }

resource "azurerm_servicebus_namespace" "adam" {
  name                = "sb-adam-${var.company_slug}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  sku                 = "Premium"
  capacity            = 4
  premium_messaging_partitions = 4
  tags                = var.tags
}

# Intent Pipeline Queue
resource "azurerm_servicebus_queue" "intent_pipeline" {
  name         = "adam-intent-pipeline"
  namespace_id = azurerm_servicebus_namespace.adam.id
  max_delivery_count = 10
  lock_duration      = "PT5M"
  max_size_in_megabytes = 81920
}

# Exception Escalation Queue
resource "azurerm_servicebus_queue" "exception_escalation" {
  name         = "adam-exception-escalation"
  namespace_id = azurerm_servicebus_namespace.adam.id
  max_delivery_count = 3
  lock_duration      = "PT2M"
}

# BOSS Scoring Topic (fan-out to all governance agents)
resource "azurerm_servicebus_topic" "boss_scoring" {
  name         = "adam-boss-scoring"
  namespace_id = azurerm_servicebus_namespace.adam.id
  max_size_in_megabytes = 81920
}

# Evidence Capture Topic
resource "azurerm_servicebus_topic" "evidence_capture" {
  name         = "adam-evidence-capture"
  namespace_id = azurerm_servicebus_namespace.adam.id
}
