# ============================================================
# ADAM DNA Deployment Specification
# Platform: Google Cloud Platform
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.10"
    }
    google-beta = {
      source  = "hashicorp/google-beta"
      version = "~> 5.10"
    }
  }
  backend "gcs" {
    bucket = "adam-tfstate-netstreamx"
    prefix = "terraform/state"
  }
}

provider "google" {
  project = var.project_id
  region  = var.primary_region
}

provider "google-beta" {
  project = var.project_id
  region  = var.primary_region
}

# ============================================================
# VPC Network - ADAM sovereignty boundaries
# ============================================================
resource "google_compute_network" "adam" {
  name                    = "adam-vpc-netstreamx"
  auto_create_subnetworks = false
  project                 = var.project_id
}

resource "google_compute_subnetwork" "governance" {
  name          = "adam-governance-subnet"
  ip_cidr_range = "10.1.0.0/16"
  region        = var.primary_region
  network       = google_compute_network.adam.id
  private_ip_google_access = true
}

resource "google_compute_subnetwork" "agents" {
  name          = "adam-agents-subnet"
  ip_cidr_range = "10.2.0.0/16"
  region        = var.primary_region
  network       = google_compute_network.adam.id

  secondary_ip_range {
    range_name    = "gke-pods"
    ip_cidr_range = "10.10.0.0/14"
  }
  secondary_ip_range {
    range_name    = "gke-services"
    ip_cidr_range = "10.20.0.0/16"
  }
}

# ============================================================
# Modules
# ============================================================
module "gke" {
  source       = "./modules/gke"
  project_id   = var.project_id
  region       = var.primary_region
  company_slug = "netstreamx"
  network      = google_compute_network.adam.name
  subnetwork   = google_compute_subnetwork.agents.name
}

module "spanner" {
  source       = "./modules/spanner"
  project_id   = var.project_id
  company_slug = "netstreamx"
}

module "gcs_evidence" {
  source       = "./modules/gcs-evidence"
  project_id   = var.project_id
  region       = var.primary_region
  company_slug = "netstreamx"
}

module "vertex_ai" {
  source       = "./modules/vertex-ai"
  project_id   = var.project_id
  region       = var.primary_region
  company_slug = "netstreamx"
}
