# ============================================================
# ADAM DNA Deployment Specification
# Platform: Google Cloud Platform
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Spanner - CORE Graph (distributed, strongly consistent)

variable "project_id" { type = string }
variable "company_slug" { type = string }

resource "google_spanner_instance" "adam_core" {
  name         = "adam-core-${var.company_slug}"
  project      = var.project_id
  config       = "regional-europe-west1"
  display_name = "ADAM CORE Engine - ${var.company_slug}"
  num_nodes    = 3

  labels = {
    "adam-component" = "core-graph"
    "adam-tier"      = "sovereign"
  }
}

resource "google_spanner_database" "core_graph" {
  instance = google_spanner_instance.adam_core.name
  name     = "adam-core-graph"
  project  = var.project_id

  ddl = [
    "CREATE TABLE Doctrine (id STRING(36) NOT NULL, type STRING(100), content JSON, version INT64, created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)) PRIMARY KEY (id)",
    "CREATE TABLE Culture (id STRING(36) NOT NULL, dimension STRING(100), value JSON, priority INT64) PRIMARY KEY (id)",
    "CREATE TABLE Objectives (id STRING(36) NOT NULL, type STRING(50), description STRING(MAX), target JSON, owner STRING(100)) PRIMARY KEY (id)",
    "CREATE TABLE Rules (id STRING(36) NOT NULL, type STRING(50), severity STRING(20), description STRING(MAX), enforcement JSON) PRIMARY KEY (id)",
    "CREATE TABLE Expectations (id STRING(36) NOT NULL, behavior STRING(MAX), exception_tolerance FLOAT64, exception_count INT64) PRIMARY KEY (id)",
    "CREATE TABLE IntentObjects (id STRING(36) NOT NULL, source JSON, desired_outcomes JSON, constraints JSON, boss_score FLOAT64, status STRING(50), created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)) PRIMARY KEY (id)",
    "CREATE TABLE BOSSScores (id STRING(36) NOT NULL, intent_id STRING(36), dimensions JSON, composite_score FLOAT64, routing_tier STRING(20), scored_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)) PRIMARY KEY (id)",
    "CREATE TABLE FlightRecorder (id STRING(36) NOT NULL, action_id STRING(36), evidence JSON, hash_chain STRING(MAX), created_at TIMESTAMP NOT NULL OPTIONS (allow_commit_timestamp=true)) PRIMARY KEY (id)",
  ]

  deletion_protection = true
}
