# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Monitoring - OpenTelemetry + Grafana + Azure Monitor

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "tags" { type = map(string) }

resource "azurerm_log_analytics_workspace" "adam" {
  name                = "law-adam-${var.company_slug}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  sku                 = "PerGB2018"
  retention_in_days   = 365
  tags                = var.tags
}

resource "azurerm_application_insights" "adam" {
  name                = "appi-adam-${var.company_slug}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  workspace_id        = azurerm_log_analytics_workspace.adam.id
  application_type    = "other"
  tags                = var.tags
}

resource "azurerm_dashboard_grafana" "adam" {
  name                = "grafana-adam-${var.company_slug}-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  grafana_major_version = "10"

  identity {
    type = "SystemAssigned"
  }

  tags = var.tags
}
