// // ============================================================
// ADAM DNA Deployment Specification
// Platform: Azure Local (On-Premises Failover)
// Company: NetStreamX
// Generated: 2026-03-29
// ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
// ============================================================
// This file was auto-generated by the ADAM DNA Deployment Tool
// from a completed ADAM DNA Questionnaire.
//
// ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
// GPU Agents: 42
// ============================================================
// AKS-HCI Module - Reduced agent mesh for failover
// Only governance + orchestration + 5 governors run on Azure Local

param clusterName string
param location string
param environment string

// AKS-HCI cluster for ADAM critical services
resource aksHciCluster 'Microsoft.Kubernetes/connectedClusters@2024-01-01' = {
  name: '${clusterName}-aks'
  location: location
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    agentPublicKeyCertificate: ''
    distribution: 'aks_edge_k8s'
  }
  tags: {
    'adam-company': 'NetStreamX'
    'adam-platform': 'azure-local-failover'
    'adam-mode': 'survival'
  }
}

// Note: Azure Local runs a REDUCED agent set:
// - CORE Engine (read-only graph replica)
// - Policy Enforcement (cached policies)
// - BOSS Scoring (cached weights)
// - 5 Domain Governor Agents
// - 4 Orchestration Agents
// - 3 Human Interface Agents
// - Flight Recorder (local write, sync on reconnection)
// Total: 16 agents (vs 81 in full deployment)
// Capacity: ~30% of production traffic
