#!/bin/bash
# ============================================================
# ADAM DNA Deployment Specification
# Platform: Azure Local (On-Premises Failover)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# Bootstrap script for Azure Local ADAM deployment
# Run on each Azure Local node to prepare for ADAM failover

set -euo pipefail

COMPANY="NetStreamX"
COMPANY_SLUG="netstreamx"
ADAM_VERSION="0.4"

echo "============================================================"
echo "  ADAM Azure Local Bootstrap"
echo "  Company: $COMPANY"
echo "  Mode: Failover (Survival)"
echo "============================================================"

# Phase 1: Validate Azure Local prerequisites
echo "[Phase 1] Validating prerequisites..."
command -v kubectl >/dev/null 2>&1 || { echo "kubectl not found"; exit 1; }
command -v helm >/dev/null 2>&1 || { echo "helm not found"; exit 1; }
command -v az >/dev/null 2>&1 || { echo "Azure CLI not found"; exit 1; }

# Phase 2: Apply ADAM namespaces
echo "[Phase 2] Creating ADAM namespaces..."
kubectl apply -f - <<EOF
apiVersion: v1
kind: Namespace
metadata:
  name: adam-governance
  labels:
    adam/plane: governance
    adam/mode: failover
---
apiVersion: v1
kind: Namespace
metadata:
  name: adam-agents
  labels:
    adam/plane: execution
    adam/mode: failover
---
apiVersion: v1
kind: Namespace
metadata:
  name: adam-data
  labels:
    adam/plane: data
    adam/mode: failover
EOF

# Phase 3: Deploy CORE Engine (read-only replica)
echo "[Phase 3] Deploying CORE Engine (read-only mode)..."
helm upgrade --install adam-core ./helm/adam-platform \
  --namespace adam-governance \
  --set coreEngine.mode=readonly \
  --set coreEngine.replicas=2 \
  --set agentMesh.mode=survival \
  --set global.company="$COMPANY" \
  --set global.platform=azure-local \
  --wait --timeout 10m

# Phase 4: Sync CORE Graph from primary
echo "[Phase 4] Syncing CORE Graph delta from primary..."
echo "  NOTE: This requires network connectivity to Azure primary."
echo "  If disconnected, ADAM will use the last cached CORE Graph snapshot."

# Phase 5: Deploy critical-path agents only
echo "[Phase 5] Deploying critical-path agents (16 of 81)..."
echo "  - 5 Domain Governor Agents"
echo "  - 4 Orchestration Agents"
echo "  - 3 Human Interface Agents"
echo "  - BOSS Scoring Engine"
echo "  - Policy Enforcement Engine"
echo "  - Flight Recorder (local write)"
echo "  - CORE Engine (read-only)"

# Phase 6: Validation
echo "[Phase 6] Validating deployment..."
kubectl get pods -n adam-governance
kubectl get pods -n adam-agents
kubectl get pods -n adam-data

echo ""
echo "============================================================"
echo "  ADAM Azure Local Bootstrap COMPLETE"
echo "  Status: STANDBY (waiting for failover activation)"
echo "  Capacity: ~30% of production traffic"
echo "  Disconnected mode: Up to 72 hours"
echo "============================================================"
