# ============================================================
# ADAM DNA Deployment Specification
# Platform: ADAM Configuration Bundle (Platform-Agnostic)
# Company: NetStreamX
# Generated: 2026-04-20
# ADAM Version: 1.4 | DNA Questionnaire Version: 1.0 | BOSS Formulas: v3.2
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 81+ (reference) | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM BOSS Scoring - OPA/Rego Policy (BOSS Formulas v3.2)
# 7 canonical dimensions; Priority Tier weights sum to 24.0
# Company: NetStreamX

package adam.boss

import future.keywords.in

# Canonical BOSS v3.2 Priority Tier weights (denominator Σ = 24.0)
# Top=5.0 (Security only), Very High=4.0, High=3.0, Medium=2.0
weights := {
  "security_impact": 5.0,
  "sovereignty_action": 4.0,
  "financial_exposure": 4.0,
  "regulatory_impact": 3.0,
  "reputational_risk": 3.0,
  "rights_certainty": 3.0,
  "doctrinal_alignment": 2.0
}

# Composite score calculation (weighted average, denominator 24.0)
composite_score := score {
  weighted_sum := sum([input.dimensions[d] * weights[d] | some d in object.keys(weights)])
  weight_total := sum([w | some w in object.values(weights)])
  raw := weighted_sum / weight_total

  # Critical Dimension Override: if any dim > 75, composite >= max_dim - 10
  max_dim := max([input.dimensions[d] | some d in object.keys(weights)])
  override := max_dim - 10

  base := max(raw, override) if max_dim > 75 else raw

  # Non-Idempotent Penalty: +15 flat additive (NOT a multiplier)
  penalty := 15 if input.is_non_idempotent else 0

  score := min(base + penalty, 100)
}

# Routing tier (SOAP/MODERATE/ELEVATED/HIGH/OHSHAT per ADAM book v1.4)
default routing_tier := "soap"
routing_tier := "ohshat" if composite_score > 75          # 76-100
routing_tier := "high" if composite_score > 50            # 51-75
routing_tier := "elevated" if composite_score > 30        # 31-50
routing_tier := "moderate" if composite_score > 10        # 11-30
# Implicit: 0-10 stays as default "soap"

# Escalation targets per tier (canonical ADAM routing)
escalation_targets["ohshat"] := ["CEO", "All Directors", "Automatic Safe-Mode"]
escalation_targets["high"] := ["Relevant Domain Director", "4-Hour Max Response"]
escalation_targets["elevated"] := ["Domain Governor Agent", "Structured Exception Packet"]
escalation_targets["moderate"] := ["Autonomous Execution", "Enhanced Logging", "Post-Hoc Review"]
escalation_targets["soap"] := ["Autonomous Execution", "Minimal Logging"]

# Intent validation
intent_valid {
  input.intent.intent_id != ""
  input.intent.source.role != ""
  count(input.intent.desired_outcomes) > 0
}

# Director authorization check (5-Director Constitution)
director_authorized {
  input.intent.source.role == "director"
  input.intent.source.director_id in ["ceo", "cfo", "legal_director", "market_director", "ciso", "cpo", "cto"]
}

director_authorized {
  count(input.intent.source.delegation_chain) > 0
}
