# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Bedrock - AI services for agent reasoning

variable "environment" { type = string }
variable "company_slug" { type = string }

# Note: AWS Bedrock model access is configured via the console.
# This Terraform provisions the guardrails and custom model imports.

resource "aws_bedrock_guardrail" "adam" {
  name        = "adam-governance-guardrail-${var.environment}"
  description = "ADAM governance guardrail for agent reasoning"

  blocked_input_messaging  = "This request violates ADAM governance policy."
  blocked_outputs_messaging = "This response was blocked by ADAM governance."

  content_policy_config {
    filters_config {
      type            = "SEXUAL"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "VIOLENCE"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
    filters_config {
      type            = "HATE"
      input_strength  = "HIGH"
      output_strength = "HIGH"
    }
  }
}
