# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Neptune - CORE Graph standby (Gremlin-compatible)

variable "environment" { type = string }
variable "company_slug" { type = string }
variable "vpc_id" { type = string }
variable "subnet_ids" { type = list(string) }

resource "aws_neptune_subnet_group" "adam" {
  name       = "adam-neptune-${var.environment}"
  subnet_ids = var.subnet_ids
}

resource "aws_neptune_cluster" "adam_core" {
  cluster_identifier                  = "adam-core-${var.company_slug}-${var.environment}"
  engine                              = "neptune"
  engine_version                      = "1.3.1.0"
  neptune_subnet_group_name           = aws_neptune_subnet_group.adam.name
  storage_encrypted                   = true
  deletion_protection                 = true
  iam_database_authentication_enabled = true
  backup_retention_period             = 35
  preferred_backup_window             = "02:00-03:00"
  enable_cloudwatch_logs_exports      = ["audit"]
}

resource "aws_neptune_cluster_instance" "adam_core" {
  count              = 3
  cluster_identifier = aws_neptune_cluster.adam_core.id
  instance_class     = "db.r6g.4xlarge"
  engine             = "neptune"
}
