# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Identity Module - Entra ID managed identities for zero-trust agent mesh

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "agent_count" { type = number }
variable "tags" { type = map(string) }

# AKS Cluster Managed Identity
resource "azurerm_user_assigned_identity" "aks" {
  name                = "id-adam-aks-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

# CORE Engine Managed Identity (high-privilege, governance plane)
resource "azurerm_user_assigned_identity" "core_engine" {
  name                = "id-adam-core-engine-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

# Flight Recorder Identity (append-only permissions)
resource "azurerm_user_assigned_identity" "flight_recorder" {
  name                = "id-adam-flight-recorder-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

# BOSS Scoring Engine Identity
resource "azurerm_user_assigned_identity" "boss_engine" {
  name                = "id-adam-boss-engine-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

# Agent Mesh Workload Identity (shared by all 81 agents via federated credentials)
resource "azurerm_user_assigned_identity" "agent_mesh" {
  name                = "id-adam-agent-mesh-${var.environment}"
  resource_group_name = var.resource_group_name
  location            = var.location
  tags                = var.tags
}

output "aks_identity_id" {
  value = azurerm_user_assigned_identity.aks.id
}

output "core_engine_identity_id" {
  value = azurerm_user_assigned_identity.core_engine.id
}
