"""Pydantic schema round-trip and validation tests.

The schemas are the wire format between the engine, agent frameworks,
and the Flight Recorder. We validate:

* ``IntentObject`` accepts the ADAM v1.0 payload shape;
* ``IntentObject`` round-trips losslessly through JSON;
* ``TierConfigRequest`` parses a 7-dimension assignment dict;
* ``ExceptionPacket`` requires a non-negative SLA;
* ``DecisionReceipt`` rejects short hashes.
"""

from __future__ import annotations

import sys
from datetime import datetime
from uuid import uuid4

if sys.version_info >= (3, 11):  # noqa: UP036 - py310 dev-sandbox fallback only
    from datetime import UTC
else:  # pragma: no cover - py310 dev-sandbox fallback; CODEX runs on py311+
    from datetime import timezone as _tz

    UTC = _tz.utc  # noqa: UP017 - alias required on py310

import pytest
from pydantic import ValidationError

from boss_core.schemas import (
    AlternativeAction,
    DecisionReceipt,
    EscalationTier,
    ExceptionPacket,
    IntentObject,
    IntentSource,
    TierConfigRequest,
)
from boss_core.tiers import DimensionKey, Tier


class TestIntentObject:
    def test_minimal_payload(self) -> None:
        intent = IntentObject(
            source=IntentSource(user_id="agent.demo"),
            headline="Smoke test intent",
        )
        assert intent.schema_version == "1.0"
        assert intent.is_non_idempotent is False
        assert intent.intent_id  # autogenerated

    def test_round_trip_json(self, amber_coast_intent: IntentObject) -> None:
        raw = amber_coast_intent.model_dump_json()
        restored = IntentObject.model_validate_json(raw)
        assert restored.headline == amber_coast_intent.headline
        assert restored.intent_id == amber_coast_intent.intent_id
        assert restored.dimension_inputs.security == amber_coast_intent.dimension_inputs.security

    def test_naive_timestamp_coerced_to_utc(self) -> None:
        naive = datetime(2026, 4, 22, 10, 0, 0)
        intent = IntentObject(
            source=IntentSource(user_id="agent.demo"),
            headline="Timezone coercion",
            timestamp=naive,
        )
        assert intent.timestamp.tzinfo is UTC

    def test_empty_headline_rejected(self) -> None:
        with pytest.raises(ValidationError):
            IntentObject(
                source=IntentSource(user_id="agent.demo"),
                headline="",
            )


class TestTierConfigRequest:
    def test_full_assignment_accepted(self) -> None:
        request = TierConfigRequest(
            assignments={
                DimensionKey.SECURITY: Tier.TOP,
                DimensionKey.SOVEREIGNTY: Tier.VERY_HIGH,
                DimensionKey.FINANCIAL: Tier.VERY_HIGH,
                DimensionKey.REGULATORY: Tier.HIGH,
                DimensionKey.REPUTATIONAL: Tier.HIGH,
                DimensionKey.RIGHTS: Tier.HIGH,
                DimensionKey.DOCTRINAL: Tier.MEDIUM,
            },
            author="director.alpha",
            reason="Align with ADAM v3.2 defaults",
        )
        assert request.assignments[DimensionKey.SECURITY] is Tier.TOP


class TestExceptionPacket:
    def test_happy_path(self) -> None:
        packet = ExceptionPacket(
            intent_id=uuid4(),
            result_id=uuid4(),
            escalation_tier=EscalationTier.ELEVATED,
            summary="Amber Coast EU launch",
            drivers=["regulatory:GDPR", "reputational:RepTrak"],
            required_approvers=["domain_governor.eu"],
            alternatives=[
                AlternativeAction(
                    alt_id="alt-1",
                    description="Launch in 4 countries instead of 8",
                    projected_composite=28.0,
                )
            ],
            response_sla_minutes=60,
        )
        assert packet.response_sla_minutes == 60
        assert packet.alternatives[0].projected_composite == 28.0

    def test_rejects_negative_sla(self) -> None:
        with pytest.raises(ValidationError):
            ExceptionPacket(
                intent_id=uuid4(),
                result_id=uuid4(),
                escalation_tier=EscalationTier.ELEVATED,
                summary="x",
                response_sla_minutes=-5,
            )


class TestDecisionReceipt:
    def test_requires_hash_length(self) -> None:
        with pytest.raises(ValidationError):
            DecisionReceipt(
                packet_id=uuid4(),
                intent_id=uuid4(),
                result_id=uuid4(),
                director_id="director.alpha",
                decision="APPROVE",
                prior_hash="short",
                receipt_hash="short",
            )

    def test_happy_path(self) -> None:
        receipt = DecisionReceipt(
            packet_id=uuid4(),
            intent_id=uuid4(),
            result_id=uuid4(),
            director_id="director.alpha",
            decision="APPROVE_WITH_CONSTRAINTS",
            applied_constraints=["cap_budget_5m", "eu_residency_only"],
            prior_hash="0" * 64,
            receipt_hash="a" * 64,
        )
        assert receipt.decision == "APPROVE_WITH_CONSTRAINTS"
