# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM S3 Evidence Store - Flight Recorder (immutable)

variable "environment" { type = string }
variable "company_slug" { type = string }

resource "aws_s3_bucket" "flight_recorder" {
  bucket = "adam-flight-recorder-${var.company_slug}-${var.environment}"
}

resource "aws_s3_bucket_versioning" "flight_recorder" {
  bucket = aws_s3_bucket.flight_recorder.id
  versioning_configuration { status = "Enabled" }
}

resource "aws_s3_bucket_server_side_encryption_configuration" "flight_recorder" {
  bucket = aws_s3_bucket.flight_recorder.id
  rule {
    apply_server_side_encryption_by_default {
      sse_algorithm     = "aws:kms"
      kms_master_key_id = aws_kms_key.evidence.arn
    }
  }
}

resource "aws_s3_bucket_object_lock_configuration" "flight_recorder" {
  bucket = aws_s3_bucket.flight_recorder.id
  rule {
    default_retention {
      mode = "GOVERNANCE"
      days = 2555  # 7 years
    }
  }
}

resource "aws_s3_bucket_public_access_block" "flight_recorder" {
  bucket                  = aws_s3_bucket.flight_recorder.id
  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_kms_key" "evidence" {
  description         = "ADAM Flight Recorder encryption"
  enable_key_rotation = true
}
