# ============================================================
# ADAM DNA Deployment Specification
# Platform: Azure Local (On-Premises Failover)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Azure Local Terraform - On-Premises Failover

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.90"
    }
    azapi = {
      source  = "Azure/azapi"
      version = "~> 1.10"
    }
  }
}

provider "azurerm" {
  features {}
}

# Azure Local Resource Group
resource "azurerm_resource_group" "adam_local" {
  name     = "rg-adam-local-netstreamx"
  location = var.location
  tags = {
    "adam-company"  = "NetStreamX"
    "adam-platform" = "azure-local"
    "adam-mode"     = "failover"
  }
}

# Arc-enabled Kubernetes for ADAM critical services
resource "azapi_resource" "adam_arc_cluster" {
  type      = "Microsoft.Kubernetes/connectedClusters@2024-01-01"
  name      = "adam-local-netstreamx"
  location  = var.location
  parent_id = azurerm_resource_group.adam_local.id

  identity {
    type = "SystemAssigned"
  }

  body = jsonencode({
    properties = {
      agentPublicKeyCertificate = ""
      distribution              = "aks_edge_k8s"
    }
  })
}

variable "location" {
  type    = string
  default = "westeurope"
}
