# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Cosmos DB Module - CORE Graph (Gremlin API)

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "multi_region_writes" { type = bool }
variable "secondary_regions" { type = list(string) }
variable "tags" { type = map(string) }

resource "azurerm_cosmosdb_account" "adam_core" {
  name                = "cosmos-adam-core-${var.company_slug}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  offer_type          = "Standard"
  kind                = "GlobalDocumentDB"

  enable_automatic_failover     = true
  enable_multiple_write_locations = var.multi_region_writes

  capabilities {
    name = "EnableGremlin"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 300
    max_staleness_prefix    = 100000
  }

  geo_location {
    location          = var.location
    failover_priority = 0
  }

  dynamic "geo_location" {
    for_each = var.secondary_regions
    content {
      location          = geo_location.value
      failover_priority = geo_location.key + 1
    }
  }

  tags = var.tags
}

# CORE Graph Database
resource "azurerm_cosmosdb_gremlin_database" "core_graph" {
  name                = "adam-core-graph"
  resource_group_name = var.resource_group_name
  account_name        = azurerm_cosmosdb_account.adam_core.name
  throughput          = 100000  # 100K RU/s for governance-grade performance
}

# CORE Graph Containers (Vertex Types)
resource "azurerm_cosmosdb_gremlin_graph" "doctrine" {
  name                = "doctrine"
  resource_group_name = var.resource_group_name
  account_name        = azurerm_cosmosdb_account.adam_core.name
  database_name       = azurerm_cosmosdb_gremlin_database.core_graph.name
  partition_key_path  = "/doctrineType"
  throughput          = 20000

  index_policy {
    automatic      = true
    indexing_mode  = "consistent"
    included_paths = ["/*"]
  }
}

resource "azurerm_cosmosdb_gremlin_graph" "culture" {
  name                = "culture"
  resource_group_name = var.resource_group_name
  account_name        = azurerm_cosmosdb_account.adam_core.name
  database_name       = azurerm_cosmosdb_gremlin_database.core_graph.name
  partition_key_path  = "/cultureType"
  throughput          = 10000
}

resource "azurerm_cosmosdb_gremlin_graph" "objectives" {
  name                = "objectives"
  resource_group_name = var.resource_group_name
  account_name        = azurerm_cosmosdb_account.adam_core.name
  database_name       = azurerm_cosmosdb_gremlin_database.core_graph.name
  partition_key_path  = "/objectiveType"
  throughput          = 10000
}

resource "azurerm_cosmosdb_gremlin_graph" "rules" {
  name                = "rules"
  resource_group_name = var.resource_group_name
  account_name        = azurerm_cosmosdb_account.adam_core.name
  database_name       = azurerm_cosmosdb_gremlin_database.core_graph.name
  partition_key_path  = "/ruleType"
  throughput          = 10000
}

resource "azurerm_cosmosdb_gremlin_graph" "expectations" {
  name                = "expectations"
  resource_group_name = var.resource_group_name
  account_name        = azurerm_cosmosdb_account.adam_core.name
  database_name       = azurerm_cosmosdb_gremlin_database.core_graph.name
  partition_key_path  = "/expectationType"
  throughput          = 10000
}

output "endpoint" {
  value = azurerm_cosmosdb_account.adam_core.endpoint
}

output "gremlin_endpoint" {
  value = azurerm_cosmosdb_account.adam_core.endpoint
}
