# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM AKS Module - Container orchestration for 81-agent mesh

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "vnet_subnet_id" { type = string }
variable "identity_id" { type = string }
variable "total_vcpus" { type = number }
variable "total_ram_gb" { type = number }
variable "gpu_agent_count" { type = number }
variable "tags" { type = map(string) }

resource "azurerm_kubernetes_cluster" "adam" {
  name                = "aks-adam-${var.company_slug}-${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name
  dns_prefix          = "adam-${var.company_slug}"
  kubernetes_version  = "1.29"
  sku_tier            = "Standard"

  identity {
    type         = "UserAssigned"
    identity_ids = [var.identity_id]
  }

  # System Node Pool - ADAM governance components
  default_node_pool {
    name                = "governance"
    vm_size             = "Standard_D16s_v5"
    min_count           = 3
    max_count           = 10
    enable_auto_scaling = true
    vnet_subnet_id      = var.vnet_subnet_id
    os_disk_size_gb     = 256
    zones               = [1, 2, 3]

    node_labels = {
      "adam/plane" = "governance"
      "adam/tier"  = "sovereign"
    }
  }

  network_profile {
    network_plugin    = "azure"
    network_policy    = "calico"
    load_balancer_sku = "standard"
    service_cidr      = "172.16.0.0/16"
    dns_service_ip    = "172.16.0.10"
  }

  azure_active_directory_role_based_access_control {
    managed            = true
    azure_rbac_enabled = true
  }

  oms_agent {
    log_analytics_workspace_id = "" # Set via monitoring module
  }

  tags = var.tags
}

# Agent Mesh Node Pool - CPU-intensive agents
resource "azurerm_kubernetes_cluster_node_pool" "agent_mesh" {
  name                  = "agentmesh"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.adam.id
  vm_size               = "Standard_D32s_v5"
  min_count             = 5
  max_count             = 50
  enable_auto_scaling   = true
  zones                 = [1, 2, 3]
  os_disk_size_gb       = 512

  node_labels = {
    "adam/plane"      = "execution"
    "adam/agent-type" = "cpu"
  }

  node_taints = ["adam/plane=execution:NoSchedule"]
  tags        = var.tags
}

# GPU Node Pool - Digital Twins, ML agents, reasoning agents
resource "azurerm_kubernetes_cluster_node_pool" "gpu" {
  name                  = "gpuagents"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.adam.id
  vm_size               = "Standard_NC24ads_A100_v4"
  min_count             = 2
  max_count             = 20
  enable_auto_scaling   = true
  zones                 = [1, 2]
  os_disk_size_gb       = 1024

  node_labels = {
    "adam/plane"      = "execution"
    "adam/agent-type" = "gpu"
    "adam/digital-twin" = "eligible"
  }

  node_taints = ["nvidia.com/gpu=present:NoSchedule"]
  tags        = var.tags
}

# Human Interface Node Pool - Director Portal, Trust Gateway
resource "azurerm_kubernetes_cluster_node_pool" "human_interface" {
  name                  = "humanintf"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.adam.id
  vm_size               = "Standard_D8s_v5"
  min_count             = 2
  max_count             = 10
  enable_auto_scaling   = true
  zones                 = [1, 2, 3]

  node_labels = {
    "adam/plane"      = "human-interface"
    "adam/agent-type" = "interface"
  }

  tags = var.tags
}

output "cluster_name" {
  value = azurerm_kubernetes_cluster.adam.name
}

output "cluster_id" {
  value = azurerm_kubernetes_cluster.adam.id
}
