# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM KMS - Cryptographic Authorization Vault

variable "environment" { type = string }
variable "company_slug" { type = string }

resource "aws_kms_key" "adam_vault" {
  description             = "ADAM Cryptographic Authorization Vault"
  key_usage               = "SIGN_VERIFY"
  customer_master_key_spec = "RSA_4096"
  deletion_window_in_days = 30
  enable_key_rotation     = true

  tags = { Name = "adam-crypto-vault-${var.environment}" }
}

resource "aws_kms_alias" "adam_vault" {
  name          = "alias/adam-crypto-vault-${var.environment}"
  target_key_id = aws_kms_key.adam_vault.key_id
}

resource "aws_kms_key" "adam_data" {
  description         = "ADAM data encryption key"
  enable_key_rotation = true
  tags = { Name = "adam-data-key-${var.environment}" }
}
