// // ============================================================
// ADAM DNA Deployment Specification
// Platform: Azure Local (On-Premises Failover)
// Company: NetStreamX
// Generated: 2026-03-29
// ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
// ============================================================
// This file was auto-generated by the ADAM DNA Deployment Tool
// from a completed ADAM DNA Questionnaire.
//
// ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
// GPU Agents: 42
// ============================================================
// Azure Arc Services for unified management

param clusterName string
param location string

resource arcExtensionFlux 'Microsoft.KubernetesConfiguration/extensions@2023-05-01' = {
  name: 'flux'
  scope: resourceGroup()
  properties: {
    extensionType: 'microsoft.flux'
    autoUpgradeMinorVersion: true
  }
}

resource arcExtensionMonitor 'Microsoft.KubernetesConfiguration/extensions@2023-05-01' = {
  name: 'azuremonitor-containers'
  scope: resourceGroup()
  properties: {
    extensionType: 'Microsoft.AzureMonitor.Containers'
    autoUpgradeMinorVersion: true
  }
}
