#!/bin/bash
# ============================================================
# ADAM DNA Deployment Specification
# Platform: Azure Local (On-Premises Failover)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Failover Activation Script
# MUST be explicitly authorized by CISO
# ADAM does not self-failover to Azure Local

set -euo pipefail

echo "============================================================"
echo "  ADAM FAILOVER ACTIVATION"
echo "  Company: NetStreamX"
echo "  Target: Azure Local (On-Premises)"
echo "============================================================"
echo ""
echo "  WARNING: This activates ADAM in survival mode."
echo "  Only critical-path services will be available."
echo "  CISO authorization is REQUIRED."
echo ""

read -p "Enter CISO authorization code: " AUTH_CODE
# In production, this would validate against the Crypto Vault

echo "[1/5] Activating Azure Local ADAM services..."
kubectl scale deployment --all -n adam-governance --replicas=2
kubectl scale deployment --all -n adam-agents --replicas=1

echo "[2/5] Switching DNS to Azure Local endpoints..."
echo "  NOTE: Manual DNS update required for director portal."

echo "[3/5] Enabling Flight Recorder local write mode..."
kubectl set env deployment/adam-flight-recorder -n adam-data \
  WRITE_MODE=local SYNC_ON_RECONNECT=true

echo "[4/5] Loading cached CORE Graph and policies..."
kubectl exec -n adam-governance deploy/adam-core-engine -- \
  /bin/adam-core load-cache --mode=readonly

echo "[5/5] Activating BOSS Scoring with cached weights..."
kubectl exec -n adam-governance deploy/adam-boss-engine -- \
  /bin/adam-boss activate --mode=cached

echo ""
echo "============================================================"
echo "  ADAM FAILOVER ACTIVE"
echo "  Mode: Survival (30% capacity)"
echo "  Disconnected operation: Up to 72 hours"
echo "  FAILBACK: Must be manually authorized by CISO"
echo "============================================================"
