# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================

terraform {
  required_version = ">= 1.5.0"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.30"
    }
  }
  backend "s3" {
    bucket         = "adam-tfstate-netstreamx"
    key            = "adam/terraform.tfstate"
    region         = "us-east-1"
    encrypt        = true
    dynamodb_table = "adam-tfstate-lock"
  }
}

provider "aws" {
  region = var.primary_region
  default_tags {
    tags = {
      "adam-company"  = "NetStreamX"
      "adam-version"  = "0.4"
      "adam-platform" = "aws-standby"
      "managed-by"    = "adam-dna-deployment-tool"
      "environment"   = var.environment
    }
  }
}

# ============================================================
# Module: Networking (VPC with isolation zones)
# ============================================================
module "networking" {
  source      = "./modules/networking"
  environment = var.environment
  company_slug = "netstreamx"
  vpc_cidr    = var.vpc_cidr
}

# ============================================================
# Module: EKS (Agent Mesh container orchestration)
# ============================================================
module "eks" {
  source           = "./modules/eks"
  environment      = var.environment
  company_slug     = "netstreamx"
  vpc_id           = module.networking.vpc_id
  private_subnets  = module.networking.private_subnet_ids
  total_vcpus      = 3180
  gpu_agent_count  = 42
}

# ============================================================
# Module: Neptune (CORE Graph - Gremlin API standby)
# ============================================================
module "neptune" {
  source          = "./modules/neptune"
  environment     = var.environment
  company_slug    = "netstreamx"
  vpc_id          = module.networking.vpc_id
  subnet_ids      = module.networking.data_subnet_ids
}

# ============================================================
# Module: S3 Evidence Store (Flight Recorder)
# ============================================================
module "s3_evidence" {
  source       = "./modules/s3-evidence"
  environment  = var.environment
  company_slug = "netstreamx"
}

# ============================================================
# Module: KMS (Cryptographic Authorization Vault)
# ============================================================
module "kms" {
  source       = "./modules/kms"
  environment  = var.environment
  company_slug = "netstreamx"
}

# ============================================================
# Module: Bedrock (AI Services)
# ============================================================
module "bedrock" {
  source       = "./modules/bedrock"
  environment  = var.environment
  company_slug = "netstreamx"
}
