# ============================================================
# ADAM DNA Deployment Specification
# Platform: Microsoft Azure (Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM Data Explorer - BOSS Score History & Time Series

variable "resource_group_name" { type = string }
variable "location" { type = string }
variable "environment" { type = string }
variable "company_slug" { type = string }
variable "tags" { type = map(string) }

resource "azurerm_kusto_cluster" "adam_boss" {
  name                = "adxadamboss${var.environment}"
  location            = var.location
  resource_group_name = var.resource_group_name

  sku {
    name     = "Standard_E8ads_v5"
    capacity = 3
  }

  auto_stop_enabled = false
  tags              = var.tags
}

resource "azurerm_kusto_database" "boss_history" {
  name                = "adam-boss-history"
  resource_group_name = var.resource_group_name
  location            = var.location
  cluster_name        = azurerm_kusto_cluster.adam_boss.name
  hot_cache_period    = "P90D"
  soft_delete_period  = "P1825D"  # 5 years
}
