# ============================================================
# ADAM DNA Deployment Specification
# Platform: ADAM Configuration Bundle (Platform-Agnostic)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM BOSS Scoring - OPA/Rego Policy
# Company: NetStreamX

package adam.boss

import future.keywords.in

# Dimension weights from DNA Questionnaire
weights := {"financial_exposure": 3.6, "regulatory_impact": 2.9, "rights_certainty": 4.2, "security_impact": 4.6, "doctrinal_alignment": 3.8, "reputational_risk": 3.3}

# Composite score calculation
composite_score := score {
  weighted_sum := sum([input.dimensions[d] * weights[d] | some d in object.keys(weights)])
  weight_total := sum([w | some w in object.values(weights)])
  raw := weighted_sum / weight_total

  # Critical dimension override
  max_dim := max([input.dimensions[d] | some d in object.keys(weights)])
  override := max_dim - 10

  base := max(raw, override) if max_dim > 75 else raw

  # Non-idempotent penalty
  penalty := 15 if input.is_non_idempotent else 0

  score := min(base + penalty, 100)
}

# Routing tier
default routing_tier := "soap"
routing_tier := "ohshat" if composite_score > 75
routing_tier := "high" if composite_score > 50
routing_tier := "elevated" if composite_score > 30
routing_tier := "moderate" if composite_score > 10

# Escalation targets per tier
escalation_targets["ohshat"] := ["CEO", "All Directors"]
escalation_targets["high"] := ["Relevant Domain Director"]
escalation_targets["elevated"] := ["Domain Governor Agent"]
escalation_targets["moderate"] := ["Enhanced Logging"]
escalation_targets["soap"] := ["Autonomous Execution"]

# Intent validation
intent_valid {
  input.intent.intent_id != ""
  input.intent.source.role != ""
  count(input.intent.desired_outcomes) > 0
}

# Director authorization check
director_authorized {
  input.intent.source.role == "director"
}

director_authorized {
  count(input.intent.source.delegation_chain) > 0
}
