# ============================================================
# ADAM DNA Deployment Specification
# Platform: Google Cloud Platform
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM GKE Module - Container orchestration for agent mesh

variable "project_id" { type = string }
variable "region" { type = string }
variable "company_slug" { type = string }
variable "network" { type = string }
variable "subnetwork" { type = string }

resource "google_container_cluster" "adam" {
  name     = "gke-adam-${var.company_slug}"
  location = var.region
  project  = var.project_id

  remove_default_node_pool = true
  initial_node_count       = 1

  network    = var.network
  subnetwork = var.subnetwork

  ip_allocation_policy {
    cluster_secondary_range_name  = "gke-pods"
    services_secondary_range_name = "gke-services"
  }

  private_cluster_config {
    enable_private_nodes    = true
    enable_private_endpoint = true
    master_ipv4_cidr_block  = "172.16.0.0/28"
  }

  workload_identity_config {
    workload_pool = "${var.project_id}.svc.id.goog"
  }

  release_channel {
    channel = "STABLE"
  }
}

# Governance Node Pool
resource "google_container_node_pool" "governance" {
  name       = "adam-governance"
  cluster    = google_container_cluster.adam.name
  location   = var.region
  project    = var.project_id

  autoscaling {
    min_node_count = 3
    max_node_count = 10
  }

  node_config {
    machine_type = "n2-standard-16"
    disk_size_gb = 256
    disk_type    = "pd-ssd"

    labels = {
      "adam/plane" = "governance"
      "adam/tier"  = "sovereign"
    }

    workload_metadata_config {
      mode = "GKE_METADATA"
    }
  }
}

# Agent Mesh Node Pool
resource "google_container_node_pool" "agents" {
  name       = "adam-agents"
  cluster    = google_container_cluster.adam.name
  location   = var.region
  project    = var.project_id

  autoscaling {
    min_node_count = 5
    max_node_count = 50
  }

  node_config {
    machine_type = "n2-standard-32"
    disk_size_gb = 512
    labels = { "adam/plane" = "execution" }
  }
}

# GPU Node Pool
resource "google_container_node_pool" "gpu" {
  name       = "adam-gpu"
  cluster    = google_container_cluster.adam.name
  location   = var.region
  project    = var.project_id

  autoscaling {
    min_node_count = 2
    max_node_count = 20
  }

  node_config {
    machine_type = "a2-highgpu-4g"
    disk_size_gb = 1024

    guest_accelerator {
      type  = "nvidia-tesla-a100"
      count = 4
    }

    labels = { "adam/plane" = "execution", "adam/agent-type" = "gpu" }
  }
}
