# ============================================================
# ADAM DNA Deployment Specification
# Platform: Amazon Web Services (Warm Standby / Primary)
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM VPC Networking - Isolation zones for sovereignty

variable "environment" { type = string }
variable "company_slug" { type = string }
variable "vpc_cidr" { type = string }

resource "aws_vpc" "adam" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags = { Name = "vpc-adam-${var.company_slug}-${var.environment}" }
}

# Governance Subnets (private, no internet)
resource "aws_subnet" "governance" {
  count             = 3
  vpc_id            = aws_vpc.adam.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 1)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags = { Name = "snet-adam-governance-${count.index}" }
}

# Agent Mesh Subnets
resource "aws_subnet" "agents" {
  count             = 3
  vpc_id            = aws_vpc.adam.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 10)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags = { Name = "snet-adam-agents-${count.index}" }
}

# Data Plane Subnets
resource "aws_subnet" "data" {
  count             = 3
  vpc_id            = aws_vpc.adam.id
  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 20)
  availability_zone = data.aws_availability_zones.available.names[count.index]
  tags = { Name = "snet-adam-data-${count.index}" }
}

data "aws_availability_zones" "available" {
  state = "available"
}

output "vpc_id" { value = aws_vpc.adam.id }
output "private_subnet_ids" { value = aws_subnet.agents[*].id }
output "data_subnet_ids" { value = aws_subnet.data[*].id }
