# ============================================================
# ADAM DNA Deployment Specification
# Platform: Google Cloud Platform
# Company: NetStreamX
# Generated: 2026-03-29
# ADAM Version: 0.4 | DNA Questionnaire Version: 1.0
# ============================================================
# This file was auto-generated by the ADAM DNA Deployment Tool
# from a completed ADAM DNA Questionnaire.
#
# ADAM Agents: 82 | vCPUs: 3180 | RAM: 12720 GB
# GPU Agents: 42
# ============================================================
# ADAM GCS - Flight Recorder (versioned, retention-locked)

variable "project_id" { type = string }
variable "region" { type = string }
variable "company_slug" { type = string }

resource "google_storage_bucket" "flight_recorder" {
  name          = "adam-flight-recorder-${var.company_slug}"
  location      = upper(var.region)
  project       = var.project_id
  storage_class = "STANDARD"
  force_destroy = false

  versioning { enabled = true }

  retention_policy {
    retention_period = 220752000  # 7 years in seconds
    is_locked        = true
  }

  uniform_bucket_level_access = true

  encryption {
    default_kms_key_name = google_kms_crypto_key.evidence.id
  }
}

resource "google_kms_key_ring" "adam" {
  name     = "adam-keyring-${var.company_slug}"
  location = var.region
  project  = var.project_id
}

resource "google_kms_crypto_key" "evidence" {
  name     = "adam-evidence-key"
  key_ring = google_kms_key_ring.adam.id
  rotation_period = "7776000s"  # 90 days
}
