"""Observability helpers — Prometheus counters + structured logging.

The metrics module is intentionally optional; if ``prometheus_client`` is
not installed, a no-op stub with an identical Protocol surface is used
so the engine still starts and callers can remain agnostic.
"""

from __future__ import annotations

import logging
from collections.abc import Callable
from typing import Any, Protocol

logger = logging.getLogger("boss")


def configure_logging(level: str = "INFO") -> None:
    """Configure structured logging consistently across entry points."""
    numeric = getattr(logging, level.upper(), logging.INFO)
    logging.basicConfig(
        level=numeric,
        format='{"ts":"%(asctime)s","lvl":"%(levelname)s","msg":%(message)r}',
    )


class _CounterLike(Protocol):
    """Minimal counter surface used by the engine."""

    def labels(self, *args: Any, **kwargs: Any) -> _CounterLike: ...
    def inc(self, *args: Any, **kwargs: Any) -> None: ...


class _HistogramLike(Protocol):
    """Minimal histogram surface used by the engine."""

    def observe(self, *args: Any, **kwargs: Any) -> None: ...
    def time(self) -> Callable[..., Any]: ...


class _NoopMetric:
    """Counter/histogram stub used when prometheus_client is missing."""

    def labels(self, *args: Any, **kwargs: Any) -> _NoopMetric:
        return self

    def inc(self, *_args: Any, **_kwargs: Any) -> None:
        return None

    def observe(self, *_args: Any, **_kwargs: Any) -> None:
        return None

    def time(self) -> Callable[..., Any]:
        return lambda *_a, **_k: None


SCORE_TOTAL: _CounterLike
LATENCY: _HistogramLike
EXCEPTION_COUNTER: _CounterLike
PROMETHEUS_AVAILABLE: bool


try:  # pragma: no cover - optional dependency
    from prometheus_client import Counter, Histogram, generate_latest

    SCORE_TOTAL = Counter(
        "boss_score_total",
        "Total number of BOSS scores computed, labelled by tier.",
        labelnames=("tier",),
    )
    LATENCY = Histogram(
        "boss_score_seconds",
        "Latency of BOSS score computation, seconds.",
        buckets=(0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0),
    )
    EXCEPTION_COUNTER = Counter(
        "boss_exception_total",
        "Number of exception packets generated by tier.",
        labelnames=("tier",),
    )
    PROMETHEUS_AVAILABLE = True

    def render_metrics() -> bytes:
        """Return the current Prometheus exposition format."""
        rendered: bytes = generate_latest()
        return rendered

except ModuleNotFoundError:  # pragma: no cover - fallback path
    SCORE_TOTAL = _NoopMetric()
    LATENCY = _NoopMetric()
    EXCEPTION_COUNTER = _NoopMetric()
    PROMETHEUS_AVAILABLE = False

    def render_metrics() -> bytes:
        """Return a placeholder body when Prometheus is unavailable."""
        return b"# prometheus_client not installed\n"
